# Generated by Django 4.2.1 on 2024-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dep_id", models.AutoField(primary_key=True, serialize=False)),
                ("dep_name", models.CharField(max_length=20)),
                ("roll_no", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="volunteer",
            fields=[
                ("volunteer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("guard_name", models.CharField(max_length=25)),
                ("guard_mob_no", models.IntegerField()),
                ("sex", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("department", models.CharField(max_length=25)),
                ("year", models.IntegerField()),
                ("community", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("blood_group", models.CharField(max_length=15)),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("mobile_no", models.IntegerField()),
                ("Email_id", models.EmailField(max_length=254)),
                ("year_of_enrollment", models.IntegerField()),
                ("cultural_talents", models.TextField()),
                ("hobbies", models.TextField()),
                ("roll_no", models.IntegerField(unique=True)),
            ],
        ),
    ]
