# Generated by Django 4.2.1 on 2024-02-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="volunteer_id",
            new_name="vol_id",
        ),
    ]
