# Generated by Django 4.2.1 on 2024-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="roll_no",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="roll_no",
            field=models.IntegerField(),
        ),
    ]
