# Generated by Django 4.2.1 on 2024-01-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="height",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="weight",
            field=models.IntegerField(),
        ),
    ]
