# Generated by Django 4.2.1 on 2024-01-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0002_alter_department_roll_no_alter_volunteer_roll_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventname", models.CharField(max_length=60)),
                ("date", models.DateField()),
            ],
        ),
    ]
