# Generated by Django 4.2.1 on 2024-02-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0002_rename_dept_id_programme_dept_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="even_id",
            new_name="event",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="vol_id",
            new_name="volunteer",
        ),
    ]
